#7 Feature/lint-action
BME-MIT-IET/iet-hf-2022-unholy-oil pull request #11
Opened 2022-05-11 22:46 UTC by gergoradeczki

- Added Prettier and ESLint support with dedicated config files.
- VSCode now recommends to use ESLint and Prettier extensions
- GitHub Action to check PR

2022-05-11 22:56 UTC, triszt4n requested changes
Please resolve the conflict in package-lock.json file 🧑‍🚀 

**EDIT:** Non-relevant anymore

2022-05-11 23:00 UTC, nemaberci requested changes

2022-05-11 23:00 UTC, nemaberci commented on .github/workflows/eslint.yml
> +      - main
Shouldn't this be master?

2022-05-11 23:00 UTC, nemaberci commented on .github/workflows/prettier.yml
> +      - main
Same here with master/main

2022-05-11 23:00 UTC, gergoradeczki commented on .github/workflows/eslint.yml
> +      - main
yes

2022-05-11 23:04 UTC, gergoradeczki commented on .github/workflows/eslint.yml
> +      - main
done

2022-05-11 23:04 UTC, gergoradeczki commented on .github/workflows/prettier.yml
> +      - main
done

2022-05-11 23:31 UTC, gergoradeczki commented
Please squash merge this PR to keep timeline clean

2022-05-12 09:12 UTC, nemaberci approved these changes
😎

2022-05-12 13:12 UTC, gergoradeczki commented
@triszt4n 🥺👉👈

2022-05-12 13:13 UTC, triszt4n approved these changes
Yep, all good

2022-05-12 13:13 UTC, triszt4n commented on .prettierrc.json
> +    "endOfLine": "auto"
These are nice stuff

2022-05-12 13:17 UTC, bbucsy approved these changes

2022-05-12 13:18 UTC, merged